server:
  port: 4745

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: exam
    password: 1234

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  liquibase:
   change-log: classpath:liquibase/changelog-master.yaml